"""added team_group_stats

Revision ID: 7bdac2172414
Revises: 749a2d25ad35
Create Date: 2026-03-19 14:27:01.812057

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7bdac2172414"
down_revision: Union[str, Sequence[str], None] = "749a2d25ad35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_group_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("place", sa.Integer(), nullable=False),
        sa.Column("games", sa.Integer(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("wins_ot", sa.Integer(), nullable=False),
        sa.Column("wins_st", sa.Integer(), nullable=False),
        sa.Column("loss", sa.Integer(), nullable=False),
        sa.Column("loss_ot", sa.Integer(), nullable=False),
        sa.Column("loss_st", sa.Integer(), nullable=False),
        sa.Column("goal_scored", sa.Integer(), nullable=False),
        sa.Column("goal_allowed", sa.Integer(), nullable=False),
        sa.Column("plus_minus", sa.Integer(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_team_group_stats_id"), "team_group_stats", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_team_group_stats_id"), table_name="team_group_stats")
    op.drop_table("team_group_stats")
    # ### end Alembic commands ###
